baseURL = "http://patrick.engineering"
languageCode = "en-us"
title = "Patrick's Engineering Blog"
theme = "ppati000"

[params]
  author = "Patrick Petrovic"
  show_reading_time = true

[markup.goldmark.renderer]
  unsafe= true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -120

  [[menu.main]]
    identifier = "about"
    pre = "|&nbsp;"
    name = "About Me"
    url = "/about/"
    weight = -110
